### ISSUE TITLE
abstract public class SampleBase extends fxsampler.SampleBase

### ISSUE THREAD

**Issue by aosama** [JFXtras/jfxtras-labs-samples#4]
hi cant locate the fxsampler.samplebase

i tried to put the code in a maven pom based project so i can run it from netbeans

i keep looking to find the fxsampler.SampleBase but cant locate this class

thank you

**Comment by tbee** [comment]
FXSampler is a shared library between ControlsFX and JFXtras. It is hosted in the ControlsFX repository.

**Comment by aosama** [comment]
hi thee,

been trying to get all the code to work together to run the samples via netbeans, i got the ControlsFX repo code and again lot of issues,

my end goal is to make a radial menu object and show it in its absolute most simplest form, just a starting point to make it display some items even with no functionlities

hope u have the time to make a small minimalistic sample or point in the right direction

**Comment by tbee** [comment]
JFXtras has a samples project, which works without a glitch. You should be able to set that up.

**Comment by tbee** [comment]
closed because of no response
