### ISSUE TITLE
 Cannot perform signing task ':signArchives' because it has no configured signatory

### ISSUE THREAD

**Issue by okuc** [JFXtras/jfxtras-labs-samples#6]
Under win10, I would like to compile it, the following error message:

`
:classes UP-TO-DATE
:jar UP-TO-DATE
:signArchives FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':signArchives'.
  > Cannot perform signing task ':signArchives' because it has no configured signatory

`
Can anyone tell me why this is, thank you！

**Comment by tbee** [comment]
Because I will not distribute the certificate which I use to sign the jar with. You need to get your own.
